language: go

go:
- "1.13"

cache:
  directories:
  - $HOME/tmp/kubebuilder
  - $HOME/.cache/go-build
  - $HOME/gopath/pkg/mod

before_install:
- GO111MODULE=on go get sigs.k8s.io/kustomize/kustomize/v3@v3.3.0
- $TRAVIS_BUILD_DIR/install-kb.sh
- export PATH=$PATH:/usr/local/kubebuilder/bin

script:
- go mod download
- make manager
- ./go.test.sh

after_success:
- bash <(curl -s https://codecov.io/bash)
