language: go

go:
- "1.13"

cache:
  directories:
  - /usr/local/kubebuilder

before_install:
- export GO111MODULE=on
- export PATH=$PATH:/usr/local/kubebuilder/bin
- go install sigs.k8s.io/kustomize/kustomize/v3
- $TRAVIS_BUILD_DIR/install-kb.sh

script:
- go mod download
- make manager
- make test
