// +build !ignore_autogenerated

/*

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KV) DeepCopyInto(out *KV) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KV.
func (in *KV) DeepCopy() *KV {
	if in == nil {
		return nil
	}
	out := new(KV)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kmake) DeepCopyInto(out *Kmake) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kmake.
func (in *Kmake) DeepCopy() *Kmake {
	if in == nil {
		return nil
	}
	out := new(Kmake)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Kmake) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KmakeList) DeepCopyInto(out *KmakeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Kmake, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KmakeList.
func (in *KmakeList) DeepCopy() *KmakeList {
	if in == nil {
		return nil
	}
	out := new(KmakeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KmakeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KmakeNowScheduler) DeepCopyInto(out *KmakeNowScheduler) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KmakeNowScheduler.
func (in *KmakeNowScheduler) DeepCopy() *KmakeNowScheduler {
	if in == nil {
		return nil
	}
	out := new(KmakeNowScheduler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KmakeNowScheduler) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KmakeNowSchedulerList) DeepCopyInto(out *KmakeNowSchedulerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KmakeNowScheduler, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KmakeNowSchedulerList.
func (in *KmakeNowSchedulerList) DeepCopy() *KmakeNowSchedulerList {
	if in == nil {
		return nil
	}
	out := new(KmakeNowSchedulerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KmakeNowSchedulerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KmakeNowSchedulerSpec) DeepCopyInto(out *KmakeNowSchedulerSpec) {
	*out = *in
	if in.Variables != nil {
		in, out := &in.Variables, &out.Variables
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Monitor != nil {
		in, out := &in.Monitor, &out.Monitor
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KmakeNowSchedulerSpec.
func (in *KmakeNowSchedulerSpec) DeepCopy() *KmakeNowSchedulerSpec {
	if in == nil {
		return nil
	}
	out := new(KmakeNowSchedulerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KmakeRule) DeepCopyInto(out *KmakeRule) {
	*out = *in
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Commands != nil {
		in, out := &in.Commands, &out.Commands
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Prereqs != nil {
		in, out := &in.Prereqs, &out.Prereqs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KmakeRule.
func (in *KmakeRule) DeepCopy() *KmakeRule {
	if in == nil {
		return nil
	}
	out := new(KmakeRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KmakeRun) DeepCopyInto(out *KmakeRun) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KmakeRun.
func (in *KmakeRun) DeepCopy() *KmakeRun {
	if in == nil {
		return nil
	}
	out := new(KmakeRun)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KmakeRun) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KmakeRunDummy) DeepCopyInto(out *KmakeRunDummy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KmakeRunDummy.
func (in *KmakeRunDummy) DeepCopy() *KmakeRunDummy {
	if in == nil {
		return nil
	}
	out := new(KmakeRunDummy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KmakeRunFileWait) DeepCopyInto(out *KmakeRunFileWait) {
	*out = *in
	if in.Files != nil {
		in, out := &in.Files, &out.Files
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KmakeRunFileWait.
func (in *KmakeRunFileWait) DeepCopy() *KmakeRunFileWait {
	if in == nil {
		return nil
	}
	out := new(KmakeRunFileWait)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KmakeRunJob) DeepCopyInto(out *KmakeRunJob) {
	*out = *in
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KmakeRunJob.
func (in *KmakeRunJob) DeepCopy() *KmakeRunJob {
	if in == nil {
		return nil
	}
	out := new(KmakeRunJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KmakeRunList) DeepCopyInto(out *KmakeRunList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KmakeRun, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KmakeRunList.
func (in *KmakeRunList) DeepCopy() *KmakeRunList {
	if in == nil {
		return nil
	}
	out := new(KmakeRunList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KmakeRunList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KmakeRunOperation) DeepCopyInto(out *KmakeRunOperation) {
	*out = *in
	if in.Job != nil {
		in, out := &in.Job, &out.Job
		*out = new(KmakeRunJob)
		(*in).DeepCopyInto(*out)
	}
	if in.Dummy != nil {
		in, out := &in.Dummy, &out.Dummy
		*out = new(KmakeRunDummy)
		**out = **in
	}
	if in.FileWait != nil {
		in, out := &in.FileWait, &out.FileWait
		*out = new(KmakeRunFileWait)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KmakeRunOperation.
func (in *KmakeRunOperation) DeepCopy() *KmakeRunOperation {
	if in == nil {
		return nil
	}
	out := new(KmakeRunOperation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KmakeRunSpec) DeepCopyInto(out *KmakeRunSpec) {
	*out = *in
	in.KmakeRunOperation.DeepCopyInto(&out.KmakeRunOperation)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KmakeRunSpec.
func (in *KmakeRunSpec) DeepCopy() *KmakeRunSpec {
	if in == nil {
		return nil
	}
	out := new(KmakeRunSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KmakeScheduleCreate) DeepCopyInto(out *KmakeScheduleCreate) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KmakeScheduleCreate.
func (in *KmakeScheduleCreate) DeepCopy() *KmakeScheduleCreate {
	if in == nil {
		return nil
	}
	out := new(KmakeScheduleCreate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KmakeScheduleDelete) DeepCopyInto(out *KmakeScheduleDelete) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KmakeScheduleDelete.
func (in *KmakeScheduleDelete) DeepCopy() *KmakeScheduleDelete {
	if in == nil {
		return nil
	}
	out := new(KmakeScheduleDelete)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KmakeScheduleForce) DeepCopyInto(out *KmakeScheduleForce) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KmakeScheduleForce.
func (in *KmakeScheduleForce) DeepCopy() *KmakeScheduleForce {
	if in == nil {
		return nil
	}
	out := new(KmakeScheduleForce)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KmakeScheduleReset) DeepCopyInto(out *KmakeScheduleReset) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KmakeScheduleReset.
func (in *KmakeScheduleReset) DeepCopy() *KmakeScheduleReset {
	if in == nil {
		return nil
	}
	out := new(KmakeScheduleReset)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KmakeScheduleRun) DeepCopyInto(out *KmakeScheduleRun) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KmakeScheduleRun.
func (in *KmakeScheduleRun) DeepCopy() *KmakeScheduleRun {
	if in == nil {
		return nil
	}
	out := new(KmakeScheduleRun)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KmakeScheduleRun) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KmakeScheduleRunList) DeepCopyInto(out *KmakeScheduleRunList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KmakeScheduleRun, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KmakeScheduleRunList.
func (in *KmakeScheduleRunList) DeepCopy() *KmakeScheduleRunList {
	if in == nil {
		return nil
	}
	out := new(KmakeScheduleRunList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KmakeScheduleRunList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KmakeScheduleRunOperation) DeepCopyInto(out *KmakeScheduleRunOperation) {
	*out = *in
	if in.Start != nil {
		in, out := &in.Start, &out.Start
		*out = new(KmakeScheduleRunStart)
		**out = **in
	}
	if in.Restart != nil {
		in, out := &in.Restart, &out.Restart
		*out = new(KmakeScheduleRunRestart)
		**out = **in
	}
	if in.Stop != nil {
		in, out := &in.Stop, &out.Stop
		*out = new(KmakeScheduleRunStop)
		**out = **in
	}
	if in.Delete != nil {
		in, out := &in.Delete, &out.Delete
		*out = new(KmakeScheduleDelete)
		**out = **in
	}
	if in.Create != nil {
		in, out := &in.Create, &out.Create
		*out = new(KmakeScheduleCreate)
		**out = **in
	}
	if in.Reset != nil {
		in, out := &in.Reset, &out.Reset
		*out = new(KmakeScheduleReset)
		**out = **in
	}
	if in.Force != nil {
		in, out := &in.Force, &out.Force
		*out = new(KmakeScheduleForce)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KmakeScheduleRunOperation.
func (in *KmakeScheduleRunOperation) DeepCopy() *KmakeScheduleRunOperation {
	if in == nil {
		return nil
	}
	out := new(KmakeScheduleRunOperation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KmakeScheduleRunRestart) DeepCopyInto(out *KmakeScheduleRunRestart) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KmakeScheduleRunRestart.
func (in *KmakeScheduleRunRestart) DeepCopy() *KmakeScheduleRunRestart {
	if in == nil {
		return nil
	}
	out := new(KmakeScheduleRunRestart)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KmakeScheduleRunSpec) DeepCopyInto(out *KmakeScheduleRunSpec) {
	*out = *in
	in.KmakeScheduleRunOperation.DeepCopyInto(&out.KmakeScheduleRunOperation)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KmakeScheduleRunSpec.
func (in *KmakeScheduleRunSpec) DeepCopy() *KmakeScheduleRunSpec {
	if in == nil {
		return nil
	}
	out := new(KmakeScheduleRunSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KmakeScheduleRunStart) DeepCopyInto(out *KmakeScheduleRunStart) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KmakeScheduleRunStart.
func (in *KmakeScheduleRunStart) DeepCopy() *KmakeScheduleRunStart {
	if in == nil {
		return nil
	}
	out := new(KmakeScheduleRunStart)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KmakeScheduleRunStop) DeepCopyInto(out *KmakeScheduleRunStop) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KmakeScheduleRunStop.
func (in *KmakeScheduleRunStop) DeepCopy() *KmakeScheduleRunStop {
	if in == nil {
		return nil
	}
	out := new(KmakeScheduleRunStop)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KmakeSpec) DeepCopyInto(out *KmakeSpec) {
	*out = *in
	if in.Variables != nil {
		in, out := &in.Variables, &out.Variables
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]KmakeRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.PersistentVolumeClaimTemplate.DeepCopyInto(&out.PersistentVolumeClaimTemplate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KmakeSpec.
func (in *KmakeSpec) DeepCopy() *KmakeSpec {
	if in == nil {
		return nil
	}
	out := new(KmakeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KmakeStatus) DeepCopyInto(out *KmakeStatus) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KmakeStatus.
func (in *KmakeStatus) DeepCopy() *KmakeStatus {
	if in == nil {
		return nil
	}
	out := new(KmakeStatus)
	in.DeepCopyInto(out)
	return out
}
