apiVersion: bythepowerof.github.com/v1
kind: Kmake
metadata:
  name: kmake-sample
  labels:
    labels: label1
    label2: label2
    label3: labelw
spec:
  # jobTemplate:
  #   spec:
  #     template:
  #       spec:
  #         containers:
  #         - name: hello
  #           image: busybox
  #           args:
  #           - /bin/sh
  #           - -c
  #           - date; echo Hello from the Kubernetes cluster
  persistent_volume_claim_template:
    storageClassName: manual
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 3Ki
  master_image: busybox
  job_image: busybox
  rules:
  - targets:
    - task1
    doublecolon: false
    commands:
    - '@echo $@'
    - '@echo $(VAR1)'
    - '@echo $(VAR2)'
    - |-
      @echo \
      $(VAR3)
    prereqs:
    - task2
    - task3
    - file1
    - file2
    - file3
  - targets:
    - task2
    - task3
    doublecolon: true
    commands:
    - '@echo $@'
    - '@echo "VAR4 = $(VAR4)"'
    - $(call COMMAND, .)
    - $(call VAR7, ..)
    prereqs:
    - file1
    - file2
    - file3
  - targets:
    - task2
    doublecolon: true
    commands:
    - '@echo nested'
  - targets:
    - file1
    - file2
    - file3
    doublecolon: true
    commands:
    - '@echo $*'
    targetpatterns:
    - file%
  - targets:
    - file1
    doublecolon: true
    commands:
    - '@echo more file1'
  - targets:
    - .INTERMEDIATE
    doublecolon: false
    commands: []
    prereqs:
    - task1
    - task2
    - task3
  - targets:
    - .PHONY
    doublecolon: false
    commands: []
    prereqs:
    - task1
    - task2
    - task3
    - file1
    - file2
    - file3
  variables:
    .PYMAKE: '1'
    MAKE: /usr/local/opt/python/bin/python3.7 /Users/jeremymarshall/src/github/JeremyMarshall/pymake/pymake/cli/main.py
    MAKEFLAGS: wsy
    MAKELEVEL: '0'
    VAR1: var1 " append" " append2"
    VAR2: var2
    VAR3: var3
    VAR5: '"var1--var3"'
    VAR6: '"$(VAR1)--$(VAR3)" "--$(VAR5)"'
    VAR7: ls $1
    FILES: file1 file2 file3
    TASKS: task2 task3
    VAR4: var4
    INC_VAR1: "'inc_var'"
