apiVersion: bythepowerof.github.com/v1
kind: Kmake
metadata:
  name: kmake-test-app
  labels:
    app.kubernetes.io/name: kmake-test-app
    app.kubernetes.io/instance: kmake-test-app
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: main
    app.kubernetes.io/part-of: kmake-test-app
    app.kubernetes.io/managed-by: kmake
spec:
  persistent_volume_claim_template:
    storageClassName: manual
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 3Ki
  rules:
  - targets:
    - task1
    doublecolon: false
    commands:
    - '@echo test "$(VAR22)" = "lit2#hash"'
    - '# test "$(VAR22)" = "lit2#hash"'
    - '@echo $@'
    - '@echo $(VAR1)'
    - '@echo $(VAR2)'
    - "@echo \\\n$(VAR3)"
    prereqs:
    - task2
    - task3
    - file1
    - file2
    - file3
  - targets:
    - task2
    - task3
    doublecolon: true
    commands:
    - '@echo $@'
    - '@echo "VAR4 = $(VAR4)"'
    - $(call COMMAND, .)
    - $(call VAR7, ..)
    prereqs:
    - file1
    - file2
    - file3
  - targets:
    - task2
    doublecolon: true
    commands:
    - '@echo nested'
  - targets:
    - file1
    - file2
    - file3
    doublecolon: true
    commands:
    - '@echo $*'
    targetpattern: file%
  - targets:
    - file1
    doublecolon: true
    commands:
    - '@echo more file1'
  - targets:
    - folder1
    - folder2
    doublecolon: false
    commands:
    - touch $@/file1
  - targets:
    - .INTERMEDIATE
    doublecolon: false
    commands: []
    prereqs:
    - task1
    - task2
    - task3
  - targets:
    - .PHONY
    doublecolon: false
    commands: []
    prereqs:
    - task1
    - task2
    - task3
    - file1
    - file2
    - file3
    - .KMAKEVOL
    - .KMAKEINIT
    - .KMAKESLEEP
  - targets:
    - .KMAKEVOL
    doublecolon: false
    commands:
    - cp -r $(KMAKE_WORKDIR)/* $(KMAKE_VOLUME)
    prereqs:
    - /tmp/kmake-vol
  - targets:
    - .KMAKEINIT
    doublecolon: false
    commands:
    - cp -r $(KMAKE_VOLUME)/* $(KMAKE_WORKDIR)
    prereqs:
    - /Users/jeremymarshall/src/test
  - targets:
    - /tmp/kmake-vol
    - /Users/jeremymarshall/src/test
    doublecolon: false
    commands:
    - mkdir -p $@
  - targets:
    - .KMAKESLEEP
    doublecolon: false
    commands:
    - '@echo sleeping'
    - tail -f /dev/null
  variables:
    COMMAND: "\tls $1\n\t@echo \"$(VAR1) $(VAR2) $(VAR3) $(VAR4) $(VAR5) $(VAR6)\""
    VAR1: var1 " append" " append2"
    VAR2: var2
    VAR3: var3
    VAR5: '"var1--var3"'
    VAR6: '"$(VAR1)--$(VAR3)" "--$(VAR5)"'
    VAR7: ls $1
    VAR22: lit2#hash
    FILES: file1 file2 file3
    FOLDERS: folder1 folder2
    TASKS: task2 task3
    VAR4: var4
    INC_VAR1: "'inc_var'"
    KMAKE_VOLUME: /usr/share/pvc
    KMAKE_WORKDIR: /kmake




