apiVersion: bythepowerof.github.com/v1
kind: KmakeRun
metadata:
  generateName: kmakerun-sample-err-
spec:
  image: jeremymarshall/make-test:1
  command: ['make']
  kmake: kmake-sample
  targets: [ 'xxx']
