apiVersion: bythepowerof.github.com/v1
kind: KmakeNowScheduler
metadata:
  name: kmakenowscheduler-sample
  labels:
    app.kubernetes.io/name: kmakenowscheduler-sample
    app.kubernetes.io/instance: kmakenowscheduler-sample
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: scheduler
    app.kubernetes.io/part-of: kmake-test-app
    app.kubernetes.io/managed-by: kmake
spec:
  variables:
    var1: value1
    var2: value2
    var3: value3
  monitor:
    - now
