
KMAKE_VOLUME ?= /tmp/kmake-vol
KMAKE_WORKDIR ?= $(CURDIR)

.PHONY: .KMAKEVOL
.KMAKEVOL: $(KMAKE_VOLUME)
	cp -r $(KMAKE_WORKDIR)/* $(KMAKE_VOLUME)

.PHONY: .KMAKEINIT
.KMAKEINIT: $(KMAKE_WORKDIR)
	cp -r $(KMAKE_VOLUME)/* $(KMAKE_WORKDIR)

$:(KMAKE_VOLUME) $(KMAKE_WORKDIR):
	mkdir -p $@

.PHONY: .KMAKESLEEP
.KMAKESLEEP:
	@echo sleeping
	tail -f /dev/null
