
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: kmakeruns.bythepowerof.github.com
spec:
  group: bythepowerof.github.com
  names:
    kind: KmakeRun
    listKind: KmakeRunList
    plural: kmakeruns
    singular: kmakerun
  scope: ""
  validation:
    openAPIV3Schema:
      description: KmakeRun is the Schema for the kmakeruns API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: KmakeRunSpec defines the desired state of KmakeRun
          type: object
        status:
          description: KmakeRunStatus defines the observed state of KmakeRun
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
